<?php
/**
 * @file
 * Custom Styleguide module file.
 */

/**
 * Implements hook_theme().
 */
function custom_styleguide_theme($existing, $type, $theme, $path) {
  return [
        'field__field_styleguide_layouts' => [
          'base hook' => 'field',
        ],
        'field__paragraph__field_sg_column_1' => [
          'base hook' => 'paragraph',
        ],
        'field__paragraph__field_sg_column_2' => [
          'base hook' => 'paragraph',
        ],

        'field__paragraph__field_sg_hex_color' => [
          'base hook' => 'paragraph',
        ],
        'field__paragraph__field_sg_rgb_color' => [
          'base hook' => 'paragraph',
        ],

        'field__paragraph__field_sg_row_header' => [
          'base hook' => 'paragraph',
        ],
        'field__paragraph__field_sg_swatch' => [
          'base hook' => 'paragraph',
        ],
        'paragraph__styleguide_colors' => [
          'base hook' => 'paragraph',
        ],
        'paragraph__styleguide_image' => [
          'base hook' => 'paragraph',
        ],
        'paragraph__styleguide_row' => [
          'base hook' => 'paragraph',
        ],
        'paragraph__styleguide_swatch_row' => [
          'base hook' => 'paragraph',
        ],
        'paragraph__styleguide_text' => [
          'base hook' => 'paragraph',
        ],
        'paragraph__styleguide_typography_row' => [
          'base hook' => 'paragraph',
        ],
        'paragraph__styleguide_vid' => [
          'base hook' => 'paragraph',
        ],
        'paragraph__view_reference' => [
          'base hook' => 'paragraph',
        ],



/**
 * Additional templates that are available to create and customize.
 *
 */

//        'field__paragraph__field_sg_image' => [
//          'base hook' => 'paragraph',
//        ],
//        'field__paragraph__field_sg_items' => [
//          'base hook' => 'paragraph',
//        ],
//        'field__paragraph__field_sg_text_block' => [
//          'base hook' => 'paragraph',
//        ],
//        'field__paragraph__field_sg_video' => [
//          'base hook' => 'paragraph',
//        ],
//        'field__body' => [
//          'base hook' => 'node',
//        ],




  ];
}